In [16]:

#Dependencies
import requests
import json
import pandas as pd
import numpy as np
from pprint import pprint


base_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/school/districtdetail?id="
school_id = "5700086424"
url = base_url + school_id

# Attom API key
from config import attom_data
attom_data

r=requests.get(url, headers={"accept":"application/json","apikey":attom_data})
r

In [2]:
school_data = r.json()
school_data

#base_url2 = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/snapshot?postalcode=03768&minavmvalue=80000&maxavmvalue=200000"
#r2=requests.get(base_url2, headers={"accept":"application/json","apikey":attom_data})
#prop_data = r2.json()

{'status': {'version': '1.0.0',
  'code': 0,
  'msg': 'SuccessWithResult',
  'total': 1,
  'page': 1,
  'pagesize': 10,
  'responseDateTime': None,
  'transactionID': None},
 'school': [{'Identifier': {'Obdistrictnumber': '5700086424'},
   'ProfilesAndTestScores': {'DistrictSummary': {'districttype': 'DISTRICT IN SUPERVISORY UNION',
     'districtname': 'LYME SCHOOL DISTRICT',
     'county3': '009',
     'countyName': 'GRAFTON COUNTY',
     'county': '33009',
     'latitude': 43.811031,
     'longitude': -72.159683,
     'locationaddress': 'RTE 10',
     'locationcity': 'LYME',
     'fipsState': '33',
     'stateabbrev': 'NH',
     'zip54': '03768',
     'zip': '03768',
     'phone': '603-795-2125',
     'startDate': '08/29',
     'endDate': '06/15',
     'GStestrating': 5},
    'DistrictContact': {'Prefixliteral': 'Mr',
     'Firstname': 'Jeff',
     'Lastname': 'Valence',
     'Gender': 'M',
     'Englishtitle': 'Superintendent',
     'Websiteurl': 'http://www.lymeschool.org'},
    'DistrictDetail': {'educationClimateIndex': 'UNCLASSIFIED',
     'advancedPlacement': 'N',
     'beforeandafterschoolprgms': 'N',
     'blueribbonschool': 'N',
     'charterschools': 'N',
     'bilingualeducation': 'N',
     'giftedandtalented': 'N',
     'internationbaccalaureate': 'N',
     'magnetschool': 'N',
     'sitebased': 'N',
     'povertypercentage': 13.0,
     'technologymeasuretext': None,
     'totaldollarexpenditures': 2511000,
     'instructionalexpensepupil': '$10,001+',
     'AYPschools': 0,
     'AYPschoolspercent': 0.0,
     'NCLBschools': 0.0,
     'NCLBschoolspercent': 0.0},
    'DistrictSchoolInfo': {'Teachersprofessionalstaff': 25,
     'Gradespancodedistricttext': None,
     'Gradelevel1lotext': 'KINDERGARTEN',
     'Gradelevel1hitext': '8TH GRADE',
     'Numberofschools': 1,
     'Countelementary': 0,
     'Countmiddle': 0,
     'Counthigh': 0,
     'Voctech': 'N',
     'Adulteducationclasses': 'N',
     'Yearroundclasses': 'N',
     'Studentsnumberof': 200,
     'Studentsorvolumesdistrict': '100 - 299'},
    'DistrictEnrollment': {'Enrollmentbygradeprek': 0,
     'Enrollmentbygradekgtn': 0,
     'Enrollmentbygradeone': 0,
     'Enrollmentbygradetwo': 0,
     'Enrollmentbygradethree': 0,
     'Enrollmentbygradefour': 0,
     'Enrollmentbygradefive': 0,
     'Enrollmentbygradesix': 0,
     'Enrollmentbygradeseven': 0,
     'Enrollmentbygradeeight': 0,
     'Enrollmentbygradenine': 0,
     'Enrollmentbygradeten': 0,
     'Enrollmentbygradeeleven': 0,
     'Enrollmentbygradetwelve': 0,
     'Enrollmentshift': 'No Change'},
    'measurementresults': [{'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '3',
      'measure': '53',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '3',
      'measure': '71',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '4',
      'measure': '78',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '4',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '5',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '5',
      'measure': '74',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Science',
      'grade': '5',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '6',
      'measure': '80',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '6',
      'measure': '80',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '7',
      'measure': '83',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '7',
      'measure': '78',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '8',
      'measure': '89',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Science',
      'grade': '8',
      'measure': '66',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '8',
      'measure': '77',
      'insttype': 'District'}],
    'measurementtype': [{'measureTypeId': 'NH01216',
      'measuretype': 'Test',
      'measureunits': 'Percent of Students',
      'measurename': 'New Hampshire State Assessment System',
      'measureabbrev': 'NH SAS',
      'resulttype': 'Percent meeting expectations',
      'scaledefinition': '% proficient',
      'rankmax': '100',
      'year': '2018',
      'purposedescription': 'For more information about New Hampshire assessments, see the New Hampshire Department of Education'}],
    'programs': [None]},
   'Vintage': {'onboardDate': '2019-7-17'}}]}

In [25]:
#"name": "Sales (snapshot) by postal code",

base_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/sale/snapshot?postalcode=63123&page=1&pageSize=20"
s = requests.get(base_url, headers={"accept":"application/json", "apikey":attom_data})
s

In [26]:
sales_data = r.json()
sales_data

{'status': {'version': '1.0.0',
  'code': 0,
  'msg': 'SuccessWithResult',
  'total': 1,
  'page': 1,
  'pagesize': 10,
  'responseDateTime': None,
  'transactionID': None},
 'school': [{'Identifier': {'Obdistrictnumber': '5700086424'},
   'ProfilesAndTestScores': {'DistrictSummary': {'districttype': 'DISTRICT IN SUPERVISORY UNION',
     'districtname': 'LYME SCHOOL DISTRICT',
     'county3': '009',
     'countyName': 'GRAFTON COUNTY',
     'county': '33009',
     'latitude': 43.811031,
     'longitude': -72.159683,
     'locationaddress': 'RTE 10',
     'locationcity': 'LYME',
     'fipsState': '33',
     'stateabbrev': 'NH',
     'zip54': '03768',
     'zip': '03768',
     'phone': '603-795-2125',
     'startDate': '08/29',
     'endDate': '06/15',
     'GStestrating': 5},
    'DistrictContact': {'Prefixliteral': 'Mr',
     'Firstname': 'Jeff',
     'Lastname': 'Valence',
     'Gender': 'M',
     'Englishtitle': 'Superintendent',
     'Websiteurl': 'http://www.lymeschool.org'},
    'DistrictDetail': {'educationClimateIndex': 'UNCLASSIFIED',
     'advancedPlacement': 'N',
     'beforeandafterschoolprgms': 'N',
     'blueribbonschool': 'N',
     'charterschools': 'N',
     'bilingualeducation': 'N',
     'giftedandtalented': 'N',
     'internationbaccalaureate': 'N',
     'magnetschool': 'N',
     'sitebased': 'N',
     'povertypercentage': 13.0,
     'technologymeasuretext': None,
     'totaldollarexpenditures': 2511000,
     'instructionalexpensepupil': '$10,001+',
     'AYPschools': 0,
     'AYPschoolspercent': 0.0,
     'NCLBschools': 0.0,
     'NCLBschoolspercent': 0.0},
    'DistrictSchoolInfo': {'Teachersprofessionalstaff': 25,
     'Gradespancodedistricttext': None,
     'Gradelevel1lotext': 'KINDERGARTEN',
     'Gradelevel1hitext': '8TH GRADE',
     'Numberofschools': 1,
     'Countelementary': 0,
     'Countmiddle': 0,
     'Counthigh': 0,
     'Voctech': 'N',
     'Adulteducationclasses': 'N',
     'Yearroundclasses': 'N',
     'Studentsnumberof': 200,
     'Studentsorvolumesdistrict': '100 - 299'},
    'DistrictEnrollment': {'Enrollmentbygradeprek': 0,
     'Enrollmentbygradekgtn': 0,
     'Enrollmentbygradeone': 0,
     'Enrollmentbygradetwo': 0,
     'Enrollmentbygradethree': 0,
     'Enrollmentbygradefour': 0,
     'Enrollmentbygradefive': 0,
     'Enrollmentbygradesix': 0,
     'Enrollmentbygradeseven': 0,
     'Enrollmentbygradeeight': 0,
     'Enrollmentbygradenine': 0,
     'Enrollmentbygradeten': 0,
     'Enrollmentbygradeeleven': 0,
     'Enrollmentbygradetwelve': 0,
     'Enrollmentshift': 'No Change'},
    'measurementresults': [{'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '3',
      'measure': '53',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '3',
      'measure': '71',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '4',
      'measure': '78',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '4',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '5',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '5',
      'measure': '74',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Science',
      'grade': '5',
      'measure': '61',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '6',
      'measure': '80',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '6',
      'measure': '80',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '7',
      'measure': '83',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '7',
      'measure': '78',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Reading',
      'grade': '8',
      'measure': '89',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Science',
      'grade': '8',
      'measure': '66',
      'insttype': 'District'},
     {'measureTypeId': 'NH01216',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '8',
      'measure': '77',
      'insttype': 'District'}],
    'measurementtype': [{'measureTypeId': 'NH01216',
      'measuretype': 'Test',
      'measureunits': 'Percent of Students',
      'measurename': 'New Hampshire State Assessment System',
      'measureabbrev': 'NH SAS',
      'resulttype': 'Percent meeting expectations',
      'scaledefinition': '% proficient',
      'rankmax': '100',
      'year': '2018',
      'purposedescription': 'For more information about New Hampshire assessments, see the New Hampshire Department of Education'}],
    'programs': [None]},
   'Vintage': {'onboardDate': '2019-7-17'}}]}

In [37]:
# School detail - curl -X GET --header 'Accept: application/json' --header 'apikey: 736f1130096aa92549d800921bca8e8c' 'https://api.gateway.attomdata.com/propertyapi/v1.0.0/school/detail?id=00582204'
sd_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/school/detail?id=00582204"

#sd = requests.get(base_url, headers={"accept":"application/json", "apikey":attom_data})
sd = requests.get(sd_url, headers={"Accept":"application/json", "apikey":attom_data})
sd

In [38]:
school_detail = sd.json()
school_detail

{'status': {'version': '1.0.0',
  'code': 0,
  'msg': 'SuccessWithResult',
  'total': 1,
  'page': 1,
  'pagesize': 10,
  'responseDateTime': None,
  'transactionID': None},
 'school': [{'Identifier': {'OBInstID': '00582204'},
   'SchoolProfileAndDistrictInfo': {'SchoolLocation': {'COUNTY3': '510',
     'COUNTYNAME': 'ST. LOUIS CITY',
     'COUNTY': '29510',
     'geocodinglatitude': 38.610114,
     'geocodinglongitude': -90.218684,
     'locationaddress': '2156 RUSSELL BLVD',
     'locationcity': 'SAINT LOUIS',
     'fipsState': '29',
     'stateabbrev': 'MO',
     'zip54': '63104-2607',
     'ZIP': '63104',
     'Obdistrictnumber': '2900580749',
     'districttype': 'REGULAR LOCAL SCHOOL DISTRICT',
     'districtname': 'ST. LOUIS PUBLIC SCHOOLS',
     'geoid': None},
    'SchoolSummary': {'Filetypetext': 'PUBLIC',
     'buildingtypetext': 'REGULAR SCHOOL',
     'institutionname': 'MCKINLEY CLASS. LEADERSHIP AC.',
     'startDate': '08/13',
     'endDate': '05/21',
     'gradelevel1lotext': '6TH GRADE',
     'gradelevel1hitext': '12TH GRADE',
     'gradelevel1locode': '06',
     'gradelevel1hicode': '12',
     'gradespancodebldgtext': '6-12',
     'Preschool': None,
     'Elementary': None,
     'Middle': 'Y',
     'High': 'Y',
     'GStestrating': 5},
    'SchoolContact': {'phone': '314-773-0027',
     'Prefixliteral': 'Mr',
     'Firstname': 'Stephen',
     'Lastname': 'Warmack',
     'Gender': 'M',
     'Englishtitle': 'Principal',
     'Websiteurl': 'http://www.slps.org/Domain/2997'},
    'SchoolDetail': {'educationClimateIndex': 'AVERAGE',
     'advancedPlacement': 'Y',
     'beforeandafterschoolprgms': 'Y',
     'blueribbonschool': 'N',
     'charterschools': 'N',
     'giftedandtalented': 'Y',
     'internationbaccalaureate': 'N',
     'magnetschool': 'N',
     'sitebased': 'Y',
     'collegebound': 92,
     'voctech': 'Y',
     'adulteducationclasses': 'N',
     'adultother': None,
     'specialeducation': 'Y',
     'alterantiveprogram': 'N',
     'yearroundclasses': 'N',
     'ESL': 'N',
     'Povertylevel': '30 PERCENT OR MORE',
     'Instructionalexpensepupil': 7305,
     'AYPschool': 'Y'},
    'SchoolTech': {'Technologymeasuretype': 'HIGH',
     'Computergrandtotal': 100,
     'OStype': 'W'},
    'SchoolEnrollment': {'Enrollmentbygradeprek': 0,
     'Enrollmentbygradekgtn': 0,
     'Enrollmentbygradeone': 0,
     'Enrollmentbygradetwo': 0,
     'Enrollmentbygradethree': 0,
     'Enrollmentbygradefour': 0,
     'Enrollmentbygradefive': 0,
     'Enrollmentbygradesix': 115,
     'Enrollmentbygradeseven': 99,
     'Enrollmentbygradeeight': 99,
     'Enrollmentbygradenine': 92,
     'Enrollmentbygradeten': 86,
     'Enrollmentbygradeeleven': 70,
     'Enrollmentbygradetwelve': 40,
     'Enrollmentshift': '-20% to -50%',
     'Studentsnumberof': 600,
     'Studentsgrade': 85.0,
     'Studentteacher': '11'},
    'DistrictSummary': {'Obdistrictnumber': '2900580749',
     'districttype': 'REGULAR LOCAL SCHOOL DISTRICT',
     'districtname': 'ST. LOUIS CITY SCHOOL DISTRICT',
     'COUNTY3': '510',
     'COUNTYNAME': 'ST. LOUIS CITY',
     'COUNTY': '29510',
     'latitude': 38.632909,
     'longitude': -90.194594,
     'locationaddress': '801 N 11TH ST',
     'locationcity': 'SAINT LOUIS',
     'fipsState': '29',
     'stateabbrev': 'MO',
     'zip54': '63101-1015',
     'ZIP': '63101',
     'phone': '314-231-3720',
     'startDate': '08/13',
     'endDate': '05/21',
     'GStestrating': 3},
    'DistrictContact': {'Prefixliteral': 'Dr',
     'Firstname': 'Kelvin',
     'Lastname': 'Adams',
     'Gender': 'U',
     'Englishtitle': 'Superintendent',
     'Websiteurl': 'http://www.slps.org'},
    'MeasurementResults': [{'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '6',
      'measure': '83.3',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Communication Arts',
      'grade': '6',
      'measure': '84.4',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Communication Arts',
      'grade': '7',
      'measure': '84.9',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '7',
      'measure': '62.1',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Mathematics',
      'grade': '8',
      'measure': '55.8',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Communication Arts',
      'grade': '8',
      'measure': '84.5',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Government',
      'grade': 'EOC',
      'measure': '93.4',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'English II',
      'grade': 'EOC',
      'measure': '86.6',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Algebra I',
      'grade': 'EOC',
      'measure': '79.7',
      'insttype': 'School'},
     {'measureTypeId': 'MO00041',
      'year': '2018',
      'subjectName': 'Algebra II',
      'grade': 'EOC',
      'measure': '60.9',
      'insttype': 'School'}],
    'MeasurementType': [{'measureTypeId': 'MO00041',
      'measuretype': 'Test',
      'measureunits': 'Percent of Students',
      'measurename': 'Missouri Assessment Program',
      'measureabbrev': 'MAP',
      'resulttype': 'Percent meeting expectations',
      'scaledefinition': '% proficient or better',
      'rankmax': '100',
      'year': '2018',
      'purposedescription': 'The Assessment section provides professional services related to the Missouri Assessment Program (MAP) and the National Assessment of Educational Progress (NAEP).'}],
    'Programs': ['Computer Science - General',
     'Foreign Language - Spanish',
     'Vocational Education - Accounting',
     'English - English / Language Arts',
     'Special Education - Early Childhood Special Needs',
     'Social Studies / Social Sciences - Social Studies / Social Sciences']},
   'Vintage': {'onboardDate': '2019-7-17'}}]}

In [27]:
# Import the csv file with OBInstID s in it to run with the school detail API
latlon_df = pd.read_csv("../LatitudeLongitude_final.csv", usecols=[1,2,3,4,5,6])
print(latlon_df.dtypes)
latlon_df.head()

Zip Code            object
Latitude           float64
Longitude          float64
School District     object
OBInstlD             int64
GeoID               object
dtype: object

,Zip Code,Latitude,Longitude,School District,OBInstlD,GeoID
0,"St. Louis, MO 63123, USA",38.558084,-90.327783,AFFTON HIGH SCHOOL,577405,ZI63123
1,"Manchester, MO 63021, USA",38.557323,-90.535236,PARKWAY SOUTH HIGH SCHOOL,1524889,ZI63021
2,"North County, MO 63137, USA",38.747943,-90.211357,RIVERVIEW GARDENS SR. HIGH SCHOOL,579881,ZI63137
3,"St. Louis, MO 63134, USA",38.741557,-90.341893,RITENOUR SR. HIGH SCHOOL,579738,ZI63134
4,"St. Louis, MO 63144, USA",38.615747,-90.351302,BRENTWOOD HIGH SCHOOL,577625,ZI63119

In [47]:
# Set variables for the school detail we want - for example
# s_climate_index = []     #'SchoolDetail''educationClimateIndex'
# s_ap = []     #'SchoolDetail''advancedPlacement'
# s_blue = []     #'SchoolDetail''blueribbonschool'
# s_gifted = []     #'SchoolDetail''giftedandtalented'
# s_ib = []     #'SchoolDetail''internationbaccalaureate'
# s_collegebound = []     #'SchoolDetail''collegebound'
# s_poverty = []     #'SchoolDetail''Povertylevel'
# s_pupilexp = []     #'SchoolDetail''Instructionalexpensepupil'
school_details = []


# import the csv file - need OBInstID in either a list or df
# **NOTE using list temporarily to test
# OBInstID_list = ['577405','1524889']
#OBInstID_list = latlon_df['OBInstlD']
# NOTE, csv file imported in cell above.  Create list w/ OBInstID from it . . .
OBInstID_list = latlon_df['OBInstlD'].tolist()

# Set School detail url
# sd_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/school/detail?id=00582204"
sd_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/school/detail?id="

# Loop over the list of IDs for each school and grab the detail information
for OBID in OBInstID_list:
    sd = requests.get(sd_url + str(OBID), headers={"accept":"application/json", "apikey":attom_data}).json()
    school = sd['school'][0]
    school_detail = school['SchoolProfileAndDistrictInfo']['SchoolDetail']
    school_details.append(school_detail)
    #print(sd)
    #print(base_url + OBID)
    #s_climate_index.append(sd['school'][0]['SchoolDetail'])
#     s_climate_index.append(sd['school'])
#     pprint(s_climate_index)

# Create a dataframe from the list of school detail info
school_details_df = pd.DataFrame(school_details)

# Add the school ID as a column to the df in case needed it later as a key for a merge
school_details_df["OBInstID"] = OBInstID_list

In [50]:
#print(OBInstID_list)
school_details_df.head()

,educationClimateIndex,advancedPlacement,beforeandafterschoolprgms,blueribbonschool,charterschools,giftedandtalented,internationbaccalaureate,magnetschool,sitebased,collegebound,...,adulteducationclasses,adultother,specialeducation,alterantiveprogram,yearroundclasses,ESL,Povertylevel,Instructionalexpensepupil,AYPschool,OBInstID
0,BELOW AVERAGE,Y,N,N,N,N,N,N,N,91,...,N,None,Y,N,N,Y,6 - 15.9 PERCENT,5669,N,577405
1,ABOVE AVERAGE,Y,N,N,N,Y,N,N,Y,95,...,Y,Y,Y,N,N,Y,6 - 15.9 PERCENT,6840,Y,1524889
2,BELOW AVERAGE,N,N,N,N,N,N,N,N,77,...,N,None,Y,N,N,N,6 - 15.9 PERCENT,4795,N,579881
3,BELOW AVERAGE,Y,N,N,N,Y,N,N,N,85,...,N,None,Y,Y,N,Y,6 - 15.9 PERCENT,5227,N,579738
4,ABOVE AVERAGE,Y,N,N,N,Y,N,N,N,96,...,N,None,Y,N,N,Y,6 - 15.9 PERCENT,9590,Y,577625

In [51]:
# Write the school details data to a csv
school_details_df.to_csv("..\Data\school_detail.csv", encoding="utf-8", index=False)

In [70]:
GeoID_list = latlon_df['GeoID'].tolist()
print(GeoID_list)

['ZI63123', 'ZI63021', 'ZI63137', 'ZI63134', 'ZI63119', 'ZI63044', 'ZI63017', 'ZI63005', 'ZI63105', 'ZI63119', 'ZI63126', 'ZI63141', 'ZI63130', 'ZI63045', 'ZI63025', 'ZI63026', 'ZI63135', 'ZI63031', 'ZI63033', 'ZI63044', 'ZI63136', 'ZI63134', 'ZI63122', 'ZI63124', 'ZI63125', 'ZI63143', 'ZI63043', 'ZI63121', 'ZI63038', 'ZI63130']

In [97]:
# Getting the real estate data
# curl -X GET --header 'Accept: application/json' --header 'apikey: 736f1130096aa92549d800921bca8e8c' 'https://api.gateway.attomdata.com/propertyapi/v1.0.0/salestrend/snapshot?geoid=ZI63021&interval=yearly&startyear=2014&endyear=2018'

# import the csv file - need GeoID in either a list or df
# **NOTE using manual list temporarily to test
#GeoID_list = ['ZI63045']
GeoID_list = latlon_df['GeoID'].tolist()

# Set varialbes
#sales_details = []
sales_details2014 = []
sales_details2015 = []
sales_details2016 = []
sales_details2017 = []
sales_details2018 = []

# Set Real estate detail url
# re_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/salestrend/snapshot?geoid=ZI63021&interval=yearly&startyear=2014&endyear=2018"
re_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/salestrend/snapshot?interval=yearly&startyear=2014&endyear=2018&geoid="

# Loop over the list of GeoIDs representing each area and grab the sales trend information - for the past 5 years
try:
    for GeoID in GeoID_list:
        #re = requests.get(re_url + GeoID, headers={"accept":"application/json", "apikey":attom_data}).json()
        re = requests.get(re_url + str(GeoID), headers={"accept":"application/json", "apikey":attom_data}).json()
        sales2014 = re['salestrends'][0]
        sales_detail2014 = sales2014['SalesTrend']
        sales_details2014.append(sales_detail2014)
#     sales2014[GeoId] = re['salestrends'][0]['SalesTrend']
#     sales2015[GeoId] = re['salestrends'][1]['SalesTrend']
        sales2015 = re['salestrends'][1]
        sales_detail2015 = sales2015['SalesTrend']
        sales_details2015.append(sales_detail2015)
        sales2016 = re['salestrends'][2]
        sales_detail2016 = sales2016['SalesTrend']
        sales_details2016.append(sales_detail2016)
        sales2017 = re['salestrends'][3]
        sales_detail2017 = sales2017['SalesTrend']
        sales_details2017.append(sales_detail2017)
        sales2018 = re['salestrends'][4]
        sales_detail2018 = sales2018['SalesTrend']
        sales_details2018.append(sales_detail2018)
        #pprint(re)
        #print(base_url + GeoID)
# print(sales2014)
# print(sales2015)
except IndexError:
    print("IndexError on record: " + GeoID)
    sales_details2014.append({'homesalecount':'no data', 'avgsaleprice':'no data', 'medsaleprice':'no data'})
    sales_details2015.append({'homesalecount':'no data', 'avgsaleprice':'no data', 'medsaleprice':'no data'})
    sales_details2016.append({'homesalecount':'no data', 'avgsaleprice':'no data', 'medsaleprice':'no data'})
    sales_details2017.append({'homesalecount':'no data', 'avgsaleprice':'no data', 'medsaleprice':'no data'})
    sales_details2018.append({'homesalecount':'no data', 'avgsaleprice':'no data', 'medsaleprice':'no data'})
    pass

# Create a df for each year's sales trend data
sales_details2014_df = pd.DataFrame(sales_details2014)
sales_details2015_df = pd.DataFrame(sales_details2015)
sales_details2016_df = pd.DataFrame(sales_details2016)
sales_details2017_df = pd.DataFrame(sales_details2017)
sales_details2018_df = pd.DataFrame(sales_details2018)

# Add the GeoID as a column to the df in case needed it later as a key for a merge
# sales_details2014_df["GeoID"] = GeoID_list
# sales_details2015_df["GeoID"] = GeoID_list
# sales_details2016_df["GeoID"] = GeoID_list
# sales_details2017_df["GeoID"] = GeoID_list
# sales_details2018_df["GeoID"] = GeoID_list

print(sales_details2018_df.head())
sales_details2014_df

IndexError on record: ZI63045
  homesalecount avgsaleprice medsaleprice
0          1128       157649       145950
1          1025       251951       227500
2           356        67045        41725
3           177        58138        50000
4           768       272685       229000

   homesalecount avgsaleprice medsaleprice
0            891       142596       121500
1            915       219636       190000
2            255        58157        43000
3            186        49166        42250
4            699       223816       182500
5            192       126675       124250
6            660       341195       299950
7            308       598256       539950
8            315       571208       448500
9            699       223816       182500
10           261       171605       160000
11           329       376807       277305
12           479       237563       206000
13       no data      no data      no data

In [83]:
GeoID_list = ['ZI63045']
re_url = "https://api.gateway.attomdata.com/propertyapi/v1.0.0/salestrend/snapshot?interval=yearly&startyear=2014&endyear=2018&geoid="

# Loop over the list of GeoIDs representing each area and grab the sales trend information - for the past 5 years
for GeoID in GeoID_list:
    #re = requests.get(re_url + GeoID, headers={"accept":"application/json", "apikey":attom_data}).json()
    re = requests.get(re_url + str(GeoID), headers={"accept":"application/json", "apikey":attom_data}).json()
    
pprint(re)

{'salestrends': [],
 'status': {'code': 1,
            'msg': 'SuccessWithoutResult',
            'total': 0,
            'version': '1.0.0'}}